# resolve-type-names: false

class ::TenantAlias < ::ApplicationRecord
  extend ::ActiveRecord::Base::ClassMethods[::TenantAlias, ::TenantAlias::ActiveRecord_Relation, ::Integer]

  module ::TenantAlias::GeneratedAttributeMethods
    def id: () -> ::Integer

    def id=: (::Integer) -> ::Integer

    def id?: () -> bool

    def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_change: () -> [ ::Integer?, ::Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> ::Integer?

    def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def id_previous_change: () -> ::Array[::Integer?]?

    def id_previously_was: () -> ::Integer?

    def id_before_last_save: () -> ::Integer?

    def id_change_to_be_saved: () -> ::Array[::Integer?]?

    def id_in_database: () -> ::Integer?

    def saved_change_to_id: () -> ::Array[::Integer?]?

    def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def id_before_type_cast: () -> ::Integer

    def id_for_database: () -> ::Integer

    def alias_name: () -> ::String

    def alias_name=: (::String) -> ::String

    def alias_name?: () -> bool

    def alias_name_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def alias_name_change: () -> [ ::String?, ::String? ]

    def alias_name_will_change!: () -> void

    def alias_name_was: () -> ::String?

    def alias_name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

    def alias_name_previous_change: () -> ::Array[::String?]?

    def alias_name_previously_was: () -> ::String?

    def alias_name_before_last_save: () -> ::String?

    def alias_name_change_to_be_saved: () -> ::Array[::String?]?

    def alias_name_in_database: () -> ::String?

    def saved_change_to_alias_name: () -> ::Array[::String?]?

    def saved_change_to_alias_name?: (?from: ::String?, ?to: ::String?) -> bool

    def will_save_change_to_alias_name?: (?from: ::String?, ?to: ::String?) -> bool

    def restore_alias_name!: () -> void

    def clear_alias_name_change: () -> void

    def alias_name_before_type_cast: () -> ::String

    def alias_name_for_database: () -> ::String

    def created_at: () -> ::ActiveSupport::TimeWithZone

    def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def created_at?: () -> bool

    def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def created_at_will_change!: () -> void

    def created_at_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_created_at!: () -> void

    def clear_created_at_change: () -> void

    def created_at_before_type_cast: () -> ::Time

    def created_at_for_database: () -> ::Time

    def tenant_id: () -> ::Integer

    def tenant_id=: (::Integer) -> ::Integer

    def tenant_id?: () -> bool

    def tenant_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def tenant_id_change: () -> [ ::Integer?, ::Integer? ]

    def tenant_id_will_change!: () -> void

    def tenant_id_was: () -> ::Integer?

    def tenant_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def tenant_id_previous_change: () -> ::Array[::Integer?]?

    def tenant_id_previously_was: () -> ::Integer?

    def tenant_id_before_last_save: () -> ::Integer?

    def tenant_id_change_to_be_saved: () -> ::Array[::Integer?]?

    def tenant_id_in_database: () -> ::Integer?

    def saved_change_to_tenant_id: () -> ::Array[::Integer?]?

    def saved_change_to_tenant_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def will_save_change_to_tenant_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

    def restore_tenant_id!: () -> void

    def clear_tenant_id_change: () -> void

    def tenant_id_before_type_cast: () -> ::Integer

    def tenant_id_for_database: () -> ::Integer

    def updated_at: () -> ::ActiveSupport::TimeWithZone

    def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

    def updated_at?: () -> bool

    def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

    def updated_at_will_change!: () -> void

    def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

    def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

    def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

    def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

    def restore_updated_at!: () -> void

    def clear_updated_at_change: () -> void

    def updated_at_before_type_cast: () -> ::Time

    def updated_at_for_database: () -> ::Time
  end
  include ::TenantAlias::GeneratedAttributeMethods
  module ::TenantAlias::GeneratedAliasAttributeMethods
    include ::TenantAlias::GeneratedAttributeMethods

    alias id_value id

    alias id_value= id=

    alias id_value? id?

    alias id_value_changed? id_changed?

    alias id_value_change id_change

    alias id_value_will_change! id_will_change!

    alias id_value_was id_was

    alias id_value_previously_changed? id_previously_changed?

    alias id_value_previous_change id_previous_change

    alias id_value_previously_was id_previously_was

    alias id_value_before_last_save id_before_last_save

    alias id_value_change_to_be_saved id_change_to_be_saved

    alias id_value_in_database id_in_database

    alias saved_change_to_id_value saved_change_to_id

    alias saved_change_to_id_value? saved_change_to_id?

    alias will_save_change_to_id_value? will_save_change_to_id?

    alias restore_id_value! restore_id!

    alias clear_id_value_change clear_id_change

    alias id_value_before_type_cast id_before_type_cast

    alias id_value_for_database id_for_database
  end
  include ::TenantAlias::GeneratedAliasAttributeMethods

  def tenant: () -> ::Tenant
  def tenant=: (::Tenant?) -> ::Tenant?
  def reload_tenant: () -> ::Tenant?
  def build_tenant: (?untyped) -> ::Tenant
  def create_tenant: (?untyped) -> ::Tenant
  def create_tenant!: (?untyped) -> ::Tenant

  module ::TenantAlias::GeneratedAssociationMethods
  end
  include ::TenantAlias::GeneratedAssociationMethods

  module ::TenantAlias::GeneratedRelationMethods
  end

  class ::TenantAlias::ActiveRecord_Relation < ::ActiveRecord::Relation
    include ::Enumerable[::TenantAlias]
    include ::TenantAlias::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::TenantAlias, ::Integer]
  end

  class ::TenantAlias::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include ::Enumerable[::TenantAlias]
    include ::TenantAlias::GeneratedRelationMethods
    include ::ActiveRecord::Relation::Methods[::TenantAlias, ::Integer]

    def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::TenantAlias
             | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::TenantAlias]
    def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::TenantAlias
              | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::TenantAlias]
    def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::TenantAlias
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::TenantAlias]
    def reload: () -> ::Array[::TenantAlias]

    def replace: (::Array[::TenantAlias]) -> void
    def delete: (*::TenantAlias | ::Integer) -> ::Array[::TenantAlias]
    def destroy: (*::TenantAlias | ::Integer) -> ::Array[::TenantAlias]
    def <<: (*::TenantAlias | ::Array[::TenantAlias]) -> self
    def prepend: (*::TenantAlias | ::Array[::TenantAlias]) -> self
  end
end

class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Tenant < ::ApplicationRecord
end
