module Accounting
  class PropertyLedgerQuery
    @property: Property?
    @date_range: DateRange
    @limit: Integer?

    def self.call: (property: Property?, ?from: untyped, ?through: untyped, ?year: untyped, ?date_range: DateRange?, ?limit: Integer?) -> Array[ActivityRow]
    def initialize: (property: Property?, ?from: untyped, ?through: untyped, ?year: untyped, ?date_range: DateRange?, ?limit: Integer?) -> void
    def call: () -> Array[ActivityRow]

    private

    def property: () -> Property?
    def date_range: () -> DateRange
    def limit: () -> Integer?
  end
end
