module TenancyParties
  class UpdateService
    ALLOWED_ATTRIBUTES: Array[Symbol]

    def self.call: (tenancy_party: TenancyParty, ?attributes: untyped, ?params: untyped) -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)
    def initialize: (tenancy_party: TenancyParty, attributes: Hash[Symbol, untyped]) -> void
    def call: () -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)

    private

    attr_reader tenancy_party: TenancyParty
    attr_reader attributes: Hash[Symbol, untyped]
  end
end
