class PaymentIngestion
  PAYMENT_METHODS: Array[[String, String]]

  def confirmable?: () -> bool

  def confirm!: (?create_alias: bool) -> Receipt

  def duplicate_exists?: () -> bool

  def ingestion_duplicate_exists?: () -> bool

  def attachment_attached?: () -> bool

  def attachment_image?: () -> bool?
  def accounting_user: () -> User?

  private

  def validate_parse_status: () -> untyped

  def ensure_not_duplicate_payment: () -> untyped
  def prevent_mutation_after_confirmed: () -> untyped
  def prevent_destroy_if_confirmed: () -> untyped
end
