module Authentication
  def authenticated?: () -> untyped

  def require_authentication: () -> untyped

  def resume_session: () -> Session?

  def find_session_by_cookie: () -> Session?

  def request_authentication: () -> untyped

  def after_authentication_url: () -> String

  def start_new_session_for: (User user) -> Session

  def terminate_session: () -> untyped
end
