# resolve-type-names: false

interface ::_RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> ::String
  def rails_info_properties_path: (*untyped) -> ::String
  def rails_info_routes_path: (*untyped) -> ::String
  def rails_info_notes_path: (*untyped) -> ::String
  def rails_info_path: (*untyped) -> ::String
  def root_path: (*untyped) -> ::String
  def portfolio_path: (*untyped) -> ::String
  def money_path: (*untyped) -> ::String
  def inbox_path: (*untyped) -> ::String
  def reports_path: (*untyped) -> ::String
  def property_rentable_units_path: (*untyped) -> ::String
  def new_property_rentable_unit_path: (*untyped) -> ::String
  def edit_property_rentable_unit_path: (*untyped) -> ::String
  def property_rentable_unit_path: (*untyped) -> ::String
  def property_expenses_path: (*untyped) -> ::String
  def new_property_expense_path: (*untyped) -> ::String
  def property_tax_profiles_path: (*untyped) -> ::String
  def new_property_tax_profile_path: (*untyped) -> ::String
  def edit_property_tax_profile_path: (*untyped) -> ::String
  def property_tax_profile_path: (*untyped) -> ::String
  def property_tax_review_resolutions_path: (*untyped) -> ::String
  def property_tax_review_resolution_path: (*untyped) -> ::String
  def schedule_e_property_path: (*untyped) -> ::String
  def schedule_e_pdf_property_path: (*untyped) -> ::String
  def properties_path: (*untyped) -> ::String
  def new_property_path: (*untyped) -> ::String
  def edit_property_path: (*untyped) -> ::String
  def property_path: (*untyped) -> ::String
  def parties_path: (*untyped) -> ::String
  def new_party_path: (*untyped) -> ::String
  def edit_party_path: (*untyped) -> ::String
  def party_path: (*untyped) -> ::String
  def tenancy_receipts_path: (*untyped) -> ::String
  def new_tenancy_receipt_path: (*untyped) -> ::String
  def tenancy_charges_path: (*untyped) -> ::String
  def new_tenancy_charge_path: (*untyped) -> ::String
  def tenancy_tenancy_parties_path: (*untyped) -> ::String
  def new_tenancy_tenancy_party_path: (*untyped) -> ::String
  def edit_tenancy_tenancy_party_path: (*untyped) -> ::String
  def tenancy_tenancy_party_path: (*untyped) -> ::String
  def tenancy_rent_terms_path: (*untyped) -> ::String
  def new_tenancy_rent_term_path: (*untyped) -> ::String
  def receive_tenancy_security_deposit_path: (*untyped) -> ::String
  def refund_tenancy_security_deposit_path: (*untyped) -> ::String
  def apply_tenancy_security_deposit_path: (*untyped) -> ::String
  def new_tenancy_security_deposit_path: (*untyped) -> ::String
  def edit_tenancy_security_deposit_path: (*untyped) -> ::String
  def tenancy_security_deposit_path: (*untyped) -> ::String
  def statement_tenancy_path: (*untyped) -> ::String
  def tenancies_path: (*untyped) -> ::String
  def new_tenancy_path: (*untyped) -> ::String
  def edit_tenancy_path: (*untyped) -> ::String
  def tenancy_path: (*untyped) -> ::String
  def accounts_path: (*untyped) -> ::String
  def account_path: (*untyped) -> ::String
  def journal_entry_path: (*untyped) -> ::String
  def correction_security_deposit_transaction_path: (*untyped) -> ::String
  def correct_security_deposit_transaction_path: (*untyped) -> ::String
  def void_security_deposit_transaction_path: (*untyped) -> ::String
  def security_deposit_transaction_path: (*untyped) -> ::String
  def expense_reimbursements_path: (*untyped) -> ::String
  def new_expense_reimbursement_path: (*untyped) -> ::String
  def correction_expense_path: (*untyped) -> ::String
  def correct_expense_path: (*untyped) -> ::String
  def void_expense_path: (*untyped) -> ::String
  def expenses_path: (*untyped) -> ::String
  def new_expense_path: (*untyped) -> ::String
  def expense_path: (*untyped) -> ::String
  def correction_receipt_path: (*untyped) -> ::String
  def correct_receipt_path: (*untyped) -> ::String
  def void_receipt_path: (*untyped) -> ::String
  def receipts_path: (*untyped) -> ::String
  def new_receipt_path: (*untyped) -> ::String
  def receipt_path: (*untyped) -> ::String
  def void_charge_path: (*untyped) -> ::String
  def charge_path: (*untyped) -> ::String
  def download_source_document_path: (*untyped) -> ::String
  def retry_source_document_path: (*untyped) -> ::String
  def source_documents_path: (*untyped) -> ::String
  def new_source_document_path: (*untyped) -> ::String
  def source_document_path: (*untyped) -> ::String
  def confirm_imported_transaction_path: (*untyped) -> ::String
  def imported_transactions_path: (*untyped) -> ::String
  def imported_transaction_path: (*untyped) -> ::String
  def new_session_path: (*untyped) -> ::String
  def edit_session_path: (*untyped) -> ::String
  def session_path: (*untyped) -> ::String
  def passwords_path: (*untyped) -> ::String
  def new_password_path: (*untyped) -> ::String
  def edit_password_path: (*untyped) -> ::String
  def password_path: (*untyped) -> ::String
  def rails_health_check_path: (*untyped) -> ::String
  def turbo_recede_historical_location_path: (*untyped) -> ::String
  def turbo_resume_historical_location_path: (*untyped) -> ::String
  def turbo_refresh_historical_location_path: (*untyped) -> ::String
  def rails_postmark_inbound_emails_path: (*untyped) -> ::String
  def rails_relay_inbound_emails_path: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_path: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_path: (*untyped) -> ::String
  def rails_conductor_inbound_emails_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> ::String
  def rails_service_blob_path: (*untyped) -> ::String
  def rails_service_blob_proxy_path: (*untyped) -> ::String
  def rails_blob_representation_path: (*untyped) -> ::String
  def rails_blob_representation_proxy_path: (*untyped) -> ::String
  def rails_disk_service_path: (*untyped) -> ::String
  def update_rails_disk_service_path: (*untyped) -> ::String
  def rails_direct_uploads_path: (*untyped) -> ::String
  def rails_representation_path: (*untyped) -> ::String
  def rails_blob_path: (*untyped) -> ::String
  def rails_storage_proxy_path: (*untyped) -> ::String
  def rails_storage_redirect_path: (*untyped) -> ::String
  def rails_mailers_url: (*untyped) -> ::String
  def rails_info_properties_url: (*untyped) -> ::String
  def rails_info_routes_url: (*untyped) -> ::String
  def rails_info_notes_url: (*untyped) -> ::String
  def rails_info_url: (*untyped) -> ::String
  def root_url: (*untyped) -> ::String
  def portfolio_url: (*untyped) -> ::String
  def money_url: (*untyped) -> ::String
  def inbox_url: (*untyped) -> ::String
  def reports_url: (*untyped) -> ::String
  def property_rentable_units_url: (*untyped) -> ::String
  def new_property_rentable_unit_url: (*untyped) -> ::String
  def edit_property_rentable_unit_url: (*untyped) -> ::String
  def property_rentable_unit_url: (*untyped) -> ::String
  def property_expenses_url: (*untyped) -> ::String
  def new_property_expense_url: (*untyped) -> ::String
  def property_tax_profiles_url: (*untyped) -> ::String
  def new_property_tax_profile_url: (*untyped) -> ::String
  def edit_property_tax_profile_url: (*untyped) -> ::String
  def property_tax_profile_url: (*untyped) -> ::String
  def property_tax_review_resolutions_url: (*untyped) -> ::String
  def property_tax_review_resolution_url: (*untyped) -> ::String
  def schedule_e_property_url: (*untyped) -> ::String
  def schedule_e_pdf_property_url: (*untyped) -> ::String
  def properties_url: (*untyped) -> ::String
  def new_property_url: (*untyped) -> ::String
  def edit_property_url: (*untyped) -> ::String
  def property_url: (*untyped) -> ::String
  def parties_url: (*untyped) -> ::String
  def new_party_url: (*untyped) -> ::String
  def edit_party_url: (*untyped) -> ::String
  def party_url: (*untyped) -> ::String
  def tenancy_receipts_url: (*untyped) -> ::String
  def new_tenancy_receipt_url: (*untyped) -> ::String
  def tenancy_charges_url: (*untyped) -> ::String
  def new_tenancy_charge_url: (*untyped) -> ::String
  def tenancy_tenancy_parties_url: (*untyped) -> ::String
  def new_tenancy_tenancy_party_url: (*untyped) -> ::String
  def edit_tenancy_tenancy_party_url: (*untyped) -> ::String
  def tenancy_tenancy_party_url: (*untyped) -> ::String
  def tenancy_rent_terms_url: (*untyped) -> ::String
  def new_tenancy_rent_term_url: (*untyped) -> ::String
  def receive_tenancy_security_deposit_url: (*untyped) -> ::String
  def refund_tenancy_security_deposit_url: (*untyped) -> ::String
  def apply_tenancy_security_deposit_url: (*untyped) -> ::String
  def new_tenancy_security_deposit_url: (*untyped) -> ::String
  def edit_tenancy_security_deposit_url: (*untyped) -> ::String
  def tenancy_security_deposit_url: (*untyped) -> ::String
  def statement_tenancy_url: (*untyped) -> ::String
  def tenancies_url: (*untyped) -> ::String
  def new_tenancy_url: (*untyped) -> ::String
  def edit_tenancy_url: (*untyped) -> ::String
  def tenancy_url: (*untyped) -> ::String
  def accounts_url: (*untyped) -> ::String
  def account_url: (*untyped) -> ::String
  def journal_entry_url: (*untyped) -> ::String
  def correction_security_deposit_transaction_url: (*untyped) -> ::String
  def correct_security_deposit_transaction_url: (*untyped) -> ::String
  def void_security_deposit_transaction_url: (*untyped) -> ::String
  def security_deposit_transaction_url: (*untyped) -> ::String
  def expense_reimbursements_url: (*untyped) -> ::String
  def new_expense_reimbursement_url: (*untyped) -> ::String
  def correction_expense_url: (*untyped) -> ::String
  def correct_expense_url: (*untyped) -> ::String
  def void_expense_url: (*untyped) -> ::String
  def expenses_url: (*untyped) -> ::String
  def new_expense_url: (*untyped) -> ::String
  def expense_url: (*untyped) -> ::String
  def correction_receipt_url: (*untyped) -> ::String
  def correct_receipt_url: (*untyped) -> ::String
  def void_receipt_url: (*untyped) -> ::String
  def receipts_url: (*untyped) -> ::String
  def new_receipt_url: (*untyped) -> ::String
  def receipt_url: (*untyped) -> ::String
  def void_charge_url: (*untyped) -> ::String
  def charge_url: (*untyped) -> ::String
  def download_source_document_url: (*untyped) -> ::String
  def retry_source_document_url: (*untyped) -> ::String
  def source_documents_url: (*untyped) -> ::String
  def new_source_document_url: (*untyped) -> ::String
  def source_document_url: (*untyped) -> ::String
  def confirm_imported_transaction_url: (*untyped) -> ::String
  def imported_transactions_url: (*untyped) -> ::String
  def imported_transaction_url: (*untyped) -> ::String
  def new_session_url: (*untyped) -> ::String
  def edit_session_url: (*untyped) -> ::String
  def session_url: (*untyped) -> ::String
  def passwords_url: (*untyped) -> ::String
  def new_password_url: (*untyped) -> ::String
  def edit_password_url: (*untyped) -> ::String
  def password_url: (*untyped) -> ::String
  def rails_health_check_url: (*untyped) -> ::String
  def turbo_recede_historical_location_url: (*untyped) -> ::String
  def turbo_resume_historical_location_url: (*untyped) -> ::String
  def turbo_refresh_historical_location_url: (*untyped) -> ::String
  def rails_postmark_inbound_emails_url: (*untyped) -> ::String
  def rails_relay_inbound_emails_url: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_url: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_url: (*untyped) -> ::String
  def rails_conductor_inbound_emails_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> ::String
  def rails_service_blob_url: (*untyped) -> ::String
  def rails_service_blob_proxy_url: (*untyped) -> ::String
  def rails_blob_representation_url: (*untyped) -> ::String
  def rails_blob_representation_proxy_url: (*untyped) -> ::String
  def rails_disk_service_url: (*untyped) -> ::String
  def update_rails_disk_service_url: (*untyped) -> ::String
  def rails_direct_uploads_url: (*untyped) -> ::String
  def rails_representation_url: (*untyped) -> ::String
  def rails_blob_url: (*untyped) -> ::String
  def rails_storage_proxy_url: (*untyped) -> ::String
  def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
  class ::ActionController::Base
    include ::_RbsRailsPathHelpers
  end
end
