# resolve-type-names: false

interface ::_RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> ::String
  def rails_info_properties_path: (*untyped) -> ::String
  def rails_info_routes_path: (*untyped) -> ::String
  def rails_info_notes_path: (*untyped) -> ::String
  def rails_info_path: (*untyped) -> ::String
  def dashboards_index_path: (*untyped) -> ::String
  def expenses_path: (*untyped) -> ::String
  def new_expense_path: (*untyped) -> ::String
  def edit_expense_path: (*untyped) -> ::String
  def expense_path: (*untyped) -> ::String
  def tenant_payments_path: (*untyped) -> ::String
  def new_tenant_payment_path: (*untyped) -> ::String
  def edit_tenant_payment_path: (*untyped) -> ::String
  def tenant_payment_path: (*untyped) -> ::String
  def tenant_charge_path: (*untyped) -> ::String
  def scheduled_rents_path: (*untyped) -> ::String
  def new_scheduled_rent_path: (*untyped) -> ::String
  def edit_scheduled_rent_path: (*untyped) -> ::String
  def scheduled_rent_path: (*untyped) -> ::String
  def lease_tenant_payments_path: (*untyped) -> ::String
  def new_lease_tenant_payment_path: (*untyped) -> ::String
  def generate_scheduled_rents_lease_path: (*untyped) -> ::String
  def leases_path: (*untyped) -> ::String
  def new_lease_path: (*untyped) -> ::String
  def edit_lease_path: (*untyped) -> ::String
  def lease_path: (*untyped) -> ::String
  def tenants_path: (*untyped) -> ::String
  def new_tenant_path: (*untyped) -> ::String
  def edit_tenant_path: (*untyped) -> ::String
  def tenant_path: (*untyped) -> ::String
  def confirm_payment_ingestion_path: (*untyped) -> ::String
  def download_payment_ingestion_path: (*untyped) -> ::String
  def payment_ingestions_path: (*untyped) -> ::String
  def new_payment_ingestion_path: (*untyped) -> ::String
  def edit_payment_ingestion_path: (*untyped) -> ::String
  def payment_ingestion_path: (*untyped) -> ::String
  def payment_document_path: (*untyped) -> ::String
  def rental_property_expenses_path: (*untyped) -> ::String
  def new_rental_property_expense_path: (*untyped) -> ::String
  def schedule_e_rental_property_path: (*untyped) -> ::String
  def schedule_e_pdf_rental_property_path: (*untyped) -> ::String
  def rental_properties_path: (*untyped) -> ::String
  def new_rental_property_path: (*untyped) -> ::String
  def edit_rental_property_path: (*untyped) -> ::String
  def rental_property_path: (*untyped) -> ::String
  def new_session_path: (*untyped) -> ::String
  def edit_session_path: (*untyped) -> ::String
  def session_path: (*untyped) -> ::String
  def passwords_path: (*untyped) -> ::String
  def new_password_path: (*untyped) -> ::String
  def edit_password_path: (*untyped) -> ::String
  def password_path: (*untyped) -> ::String
  def rails_health_check_path: (*untyped) -> ::String
  def root_path: (*untyped) -> ::String
  def turbo_recede_historical_location_path: (*untyped) -> ::String
  def turbo_resume_historical_location_path: (*untyped) -> ::String
  def turbo_refresh_historical_location_path: (*untyped) -> ::String
  def rails_postmark_inbound_emails_path: (*untyped) -> ::String
  def rails_relay_inbound_emails_path: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_path: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_path: (*untyped) -> ::String
  def rails_conductor_inbound_emails_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_path: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> ::String
  def rails_service_blob_path: (*untyped) -> ::String
  def rails_service_blob_proxy_path: (*untyped) -> ::String
  def rails_blob_representation_path: (*untyped) -> ::String
  def rails_blob_representation_proxy_path: (*untyped) -> ::String
  def rails_disk_service_path: (*untyped) -> ::String
  def update_rails_disk_service_path: (*untyped) -> ::String
  def rails_direct_uploads_path: (*untyped) -> ::String
  def rails_representation_path: (*untyped) -> ::String
  def rails_blob_path: (*untyped) -> ::String
  def rails_storage_proxy_path: (*untyped) -> ::String
  def rails_storage_redirect_path: (*untyped) -> ::String
  def rails_mailers_url: (*untyped) -> ::String
  def rails_info_properties_url: (*untyped) -> ::String
  def rails_info_routes_url: (*untyped) -> ::String
  def rails_info_notes_url: (*untyped) -> ::String
  def rails_info_url: (*untyped) -> ::String
  def dashboards_index_url: (*untyped) -> ::String
  def expenses_url: (*untyped) -> ::String
  def new_expense_url: (*untyped) -> ::String
  def edit_expense_url: (*untyped) -> ::String
  def expense_url: (*untyped) -> ::String
  def tenant_payments_url: (*untyped) -> ::String
  def new_tenant_payment_url: (*untyped) -> ::String
  def edit_tenant_payment_url: (*untyped) -> ::String
  def tenant_payment_url: (*untyped) -> ::String
  def tenant_charge_url: (*untyped) -> ::String
  def scheduled_rents_url: (*untyped) -> ::String
  def new_scheduled_rent_url: (*untyped) -> ::String
  def edit_scheduled_rent_url: (*untyped) -> ::String
  def scheduled_rent_url: (*untyped) -> ::String
  def lease_tenant_payments_url: (*untyped) -> ::String
  def new_lease_tenant_payment_url: (*untyped) -> ::String
  def generate_scheduled_rents_lease_url: (*untyped) -> ::String
  def leases_url: (*untyped) -> ::String
  def new_lease_url: (*untyped) -> ::String
  def edit_lease_url: (*untyped) -> ::String
  def lease_url: (*untyped) -> ::String
  def tenants_url: (*untyped) -> ::String
  def new_tenant_url: (*untyped) -> ::String
  def edit_tenant_url: (*untyped) -> ::String
  def tenant_url: (*untyped) -> ::String
  def confirm_payment_ingestion_url: (*untyped) -> ::String
  def download_payment_ingestion_url: (*untyped) -> ::String
  def payment_ingestions_url: (*untyped) -> ::String
  def new_payment_ingestion_url: (*untyped) -> ::String
  def edit_payment_ingestion_url: (*untyped) -> ::String
  def payment_ingestion_url: (*untyped) -> ::String
  def payment_document_url: (*untyped) -> ::String
  def rental_property_expenses_url: (*untyped) -> ::String
  def new_rental_property_expense_url: (*untyped) -> ::String
  def schedule_e_rental_property_url: (*untyped) -> ::String
  def schedule_e_pdf_rental_property_url: (*untyped) -> ::String
  def rental_properties_url: (*untyped) -> ::String
  def new_rental_property_url: (*untyped) -> ::String
  def edit_rental_property_url: (*untyped) -> ::String
  def rental_property_url: (*untyped) -> ::String
  def new_session_url: (*untyped) -> ::String
  def edit_session_url: (*untyped) -> ::String
  def session_url: (*untyped) -> ::String
  def passwords_url: (*untyped) -> ::String
  def new_password_url: (*untyped) -> ::String
  def edit_password_url: (*untyped) -> ::String
  def password_url: (*untyped) -> ::String
  def rails_health_check_url: (*untyped) -> ::String
  def root_url: (*untyped) -> ::String
  def turbo_recede_historical_location_url: (*untyped) -> ::String
  def turbo_resume_historical_location_url: (*untyped) -> ::String
  def turbo_refresh_historical_location_url: (*untyped) -> ::String
  def rails_postmark_inbound_emails_url: (*untyped) -> ::String
  def rails_relay_inbound_emails_url: (*untyped) -> ::String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> ::String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> ::String
  def rails_mandrill_inbound_emails_url: (*untyped) -> ::String
  def rails_mailgun_inbound_emails_url: (*untyped) -> ::String
  def rails_conductor_inbound_emails_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_url: (*untyped) -> ::String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> ::String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> ::String
  def rails_service_blob_url: (*untyped) -> ::String
  def rails_service_blob_proxy_url: (*untyped) -> ::String
  def rails_blob_representation_url: (*untyped) -> ::String
  def rails_blob_representation_proxy_url: (*untyped) -> ::String
  def rails_disk_service_url: (*untyped) -> ::String
  def update_rails_disk_service_url: (*untyped) -> ::String
  def rails_direct_uploads_url: (*untyped) -> ::String
  def rails_representation_url: (*untyped) -> ::String
  def rails_blob_url: (*untyped) -> ::String
  def rails_storage_proxy_url: (*untyped) -> ::String
  def rails_storage_redirect_url: (*untyped) -> ::String
end

module ::ActionController
  class ::ActionController::Base
    include ::_RbsRailsPathHelpers
  end
end
