module ImportedTransactionsHelper
  def imported_transaction_alias_proposal: (ImportedTransaction transaction) -> String?
  def imported_transaction_source_description: (ImportedTransaction transaction) -> String
end
