require "test_helper"

class ScheduledRentsGeneratorTest < ActiveSupport::TestCase
  setup do
    @property = rental_properties(:one)
    # We use a lease that doesn't trigger callbacks or we just clean up
    @lease = Lease.create!(
      rental_property: @property,
      commencement_date: Date.new(2025, 1, 1),
      annual_rental_amount: 12000,
      lease_type: :term,
      termination_date: Date.new(2025, 12, 31)
    )
    # Clear rents generated by callback to test generator in isolation
    @lease.scheduled_rents.destroy_all
  end

  test "generates 12 rents for a full year term lease" do
    assert_difference "@lease.scheduled_rents.count", 12 do
      ScheduledRentsGenerator.new(@lease, 2025).call
    end

    first_rent = @lease.scheduled_rents.order(:due_date).first
    assert_equal Date.new(2025, 1, 1), first_rent.due_date
    assert_equal 1000.0, first_rent.amount.to_f
  end

  test "does not generate duplicate rents for the same month" do
    ScheduledRentsGenerator.new(@lease, 2025).call
    assert_no_difference "@lease.scheduled_rents.count" do
      ScheduledRentsGenerator.new(@lease, 2025).call
    end
  end

  test "skips months before lease commencement" do
    @lease.update!(commencement_date: Date.new(2025, 6, 1))
    @lease.scheduled_rents.destroy_all

    assert_difference "@lease.scheduled_rents.count", 7 do # June to Dec
      ScheduledRentsGenerator.new(@lease, 2025).call
    end

    assert_equal Date.new(2025, 6, 1), @lease.scheduled_rents.order(:due_date).first.due_date
  end

  test "skips months after lease termination" do
    @lease.update!(termination_date: Date.new(2025, 6, 30))
    @lease.scheduled_rents.destroy_all

    assert_difference "@lease.scheduled_rents.count", 6 do # Jan to June
      ScheduledRentsGenerator.new(@lease, 2025).call
    end

    assert_equal Date.new(2025, 6, 1), @lease.scheduled_rents.order(:due_date).last.due_date
  end

  test "respects end_date parameter" do
    assert_difference "@lease.scheduled_rents.count", 3 do # Jan to March
      ScheduledRentsGenerator.new(@lease, 2025, end_date: Date.new(2025, 3, 31)).call
    end
  end

  test "maintains the day of the month from commencement date" do
    @lease.update!(commencement_date: Date.new(2025, 1, 15))
    @lease.scheduled_rents.destroy_all

    ScheduledRentsGenerator.new(@lease, 2025).call

    @lease.scheduled_rents.each do |rent|
      assert_equal 15, rent.due_date.day
    end
  end
end
