require "test_helper"

class ScheduledRentsGeneratorTest < ActiveSupport::TestCase
  setup do
    @property = rental_properties(:one)
    # We use a lease that doesn't trigger callbacks or we just clean up
    @lease = Lease.create!(
      rental_property: @property,
      commencement_date: Date.new(2025, 1, 1),
      annual_rental_amount: 12000,
      lease_type: :term,
      termination_date: Date.new(2025, 12, 31)
    )
    # Clear rents generated by callback to test generator in isolation
    @lease.scheduled_rents.destroy_all
  end

  test "generates 12 rents for a full year term lease" do
    assert_difference "@lease.scheduled_rents.count", 12 do
      ScheduledRentsGenerator.new(@lease, 2025).call
    end

    first_rent = @lease.scheduled_rents.order(:due_date).first
    assert_equal Date.new(2025, 1, 1), first_rent.due_date
    assert_equal 1000.0, first_rent.amount.to_f
  end

  test "does not generate duplicate rents for the same month" do
    ScheduledRentsGenerator.new(@lease, 2025).call
    assert_no_difference "@lease.scheduled_rents.count" do
      ScheduledRentsGenerator.new(@lease, 2025).call
    end
  end

  test "skips months before lease commencement" do
    @lease.update!(commencement_date: Date.new(2025, 6, 1))
    @lease.scheduled_rents.destroy_all

    assert_difference "@lease.scheduled_rents.count", 7 do # June to Dec
      ScheduledRentsGenerator.new(@lease, 2025).call
    end

    assert_equal Date.new(2025, 6, 1), @lease.scheduled_rents.order(:due_date).first.due_date
  end

  test "skips months after lease termination" do
    @lease.update!(termination_date: Date.new(2025, 6, 30))
    @lease.scheduled_rents.destroy_all

    assert_difference "@lease.scheduled_rents.count", 6 do # Jan to June
      ScheduledRentsGenerator.new(@lease, 2025).call
    end

    assert_equal Date.new(2025, 6, 1), @lease.scheduled_rents.order(:due_date).last.due_date
  end

  test "respects end_date parameter" do
    assert_difference "@lease.scheduled_rents.count", 3 do # Jan to March
      ScheduledRentsGenerator.new(@lease, 2025, end_date: Date.new(2025, 3, 31)).call
    end
  end

  test "aligns due dates to the 1st of the month, ensuring first_due_date is on or after the commencement date" do
    # Commencement 15th (not day 1, so first due date must be after commencement: 2025-02-01)
    @lease.update!(commencement_date: Date.new(2025, 1, 15))
    @lease.scheduled_rents.destroy_all
    ScheduledRentsGenerator.new(@lease, 2025).call

    assert_equal Date.new(2025, 2, 1), @lease.scheduled_rents.order(:due_date).first.due_date
    @lease.scheduled_rents.each do |rent|
      assert_equal 1, rent.due_date.day
    end

    # Commencement 1st (is day 1, so first due date is equal to commencement: 2025-01-01)
    @lease.update!(commencement_date: Date.new(2025, 1, 1))
    @lease.scheduled_rents.destroy_all
    ScheduledRentsGenerator.new(@lease, 2025).call

    assert_equal Date.new(2025, 1, 1), @lease.scheduled_rents.order(:due_date).first.due_date
    @lease.scheduled_rents.each do |rent|
      assert_equal 1, rent.due_date.day
    end
  end

  test "truncates monthly rent and ignores remaining cents for term series" do
    # $10,000 / year term lease -> $833.33 for all 12 months
    @lease.update!(
      commencement_date: Date.new(2025, 1, 1),
      termination_date: Date.new(2025, 12, 31),
      annual_rental_amount: 10000.00
    )
    @lease.scheduled_rents.destroy_all
    ScheduledRentsGenerator.new(@lease, 2025).call

    rents = @lease.scheduled_rents.order(:due_date).to_a
    assert_equal 12, rents.size

    # All 12 months: $833.33 exactly
    rents.each do |rent|
      assert_equal 833.33, rent.amount.to_f
    end
  end
end
