module Charges
  class CreateReimbursementService
    def self.call: (
      expense: Expense,
      tenancy: Tenancy,
      ?amount_cents: Integer?,
      ?amount: (BigDecimal | Numeric | String)?,
      ?charge_date: Date?,
      ?due_on: Date?,
      ?description: String?
    ) -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)

    def initialize: (
      expense: Expense,
      tenancy: Tenancy,
      ?amount_cents: Integer?,
      ?amount: (BigDecimal | Numeric | String)?,
      ?charge_date: Date?,
      ?due_on: Date?,
      ?description: String?
    ) -> void

    def call: () -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)

    private

    attr_reader expense: Expense
    attr_reader tenancy: Tenancy
    attr_reader amount_cents: Integer?
    attr_reader amount: (BigDecimal | Numeric | String)?
    attr_reader charge_date: Date
    attr_reader due_on: Date
    attr_reader description: String?

    def parse_cents: () -> Integer?
  end
end
