class ChargesController < ApplicationController
  @tenancy: Tenancy
  @charge: Charge
  @balance_cents: Integer
  @recent_activity_rows: Array[Accounting::TenantReceivableActivityQuery::StatementRow]

  def new: () -> void
  def show: () -> void
  def create: () -> void
  def void: () -> void

  private

  def set_tenancy: () -> void
  def set_charge: () -> void
  def charge_params: () -> ActionController::Parameters
  def render_charge_failure: () -> void
end
