class ExpensesController < ApplicationController
  @expense: Expense
  @expenses: Expense::ActiveRecord_Relation
  @nested_property: Property?
  @properties: Property::ActiveRecord_Relation
  @financial_items: Array[Hash[Symbol, untyped]]
  @year: Integer

  def index: () -> untyped
  def show: () -> untyped
  def new: () -> untyped
  def create: () -> untyped
  def correction: () -> untyped
  def correct: () -> untyped
  def void: () -> untyped

  private

  def set_expense: () -> untyped
  def set_nested_property: () -> untyped
  def set_form_data: () -> untyped
  def expense_params: () -> untyped
end
