class ExpensesController < ApplicationController
  @expense: Expense
  @expenses: Expense::ActiveRecord_Relation
  @rental_property: RentalProperty?
  @rental_properties: RentalProperty::ActiveRecord_Relation
  @leases: Lease::ActiveRecord_Relation
  @financial_items: Array[untyped]
  @year: Integer

  def index: () -> untyped

  def show: () -> untyped

  def new: () -> untyped

  def edit: () -> untyped

  def create: () -> untyped

  def update: () -> untyped

  def destroy: () -> untyped

  private

  def set_expense: () -> untyped

  def set_rental_property: () -> untyped

  def set_form_data: () -> untyped

  def expense_params: () -> untyped
end
