class ExpenseReimbursementsController < ApplicationController
  @expense: Expense
  @tenancies: untyped
  @charge: Charge

  def new: () -> void
  def create: () -> void

  private

  def set_expense: () -> void
  def set_eligible_tenancies: () -> void
  def reimbursement_params: () -> ActionController::Parameters
end
