class PropertiesController < ApplicationController
  @properties: Property::ActiveRecord_Relation
  @property: Property
  @tenancies: Array[Tenancy]
  @balances: Hash[Integer, Integer]
  @ytd_summary: Accounting::PropertySummaryQuery::SummaryResult
  @recent_activity: Array[Accounting::ActivityRow]
  @security_deposits_held_cents: Integer
  @date_range: Accounting::DateRange
  @year: Integer
  @schedule_e_result: TaxReporting::ScheduleEResult
  @tax_profile: PropertyTaxProfile?
  @form_definition: TaxReporting::ScheduleEFormDefinition

  def index: () -> void
  def show: () -> void
  def schedule_e: () -> void
  def schedule_e_pdf: () -> void
  def new: () -> void
  def edit: () -> void
  def create: () -> void
  def update: () -> void
  def destroy: () -> void

  private

  def set_property: () -> Property
  def property_params: () -> ActionController::Parameters
  def unit_params: () -> ActionController::Parameters?
end
