class PropertyTaxReviewResolutionsController < ApplicationController
  @property: Property
  @resolution: PropertyTaxReviewResolution

  def create: () -> void
  def destroy: () -> void

  private

  def set_property: () -> Property
  def resolution_params: () -> ActionController::Parameters
end
