class PropertiesController < ApplicationController
  @properties: Property::ActiveRecord_Relation
  @property: Property
  @date_range: Accounting::DateRange
  @year: Integer
  @financial_activity: Array[Accounting::ActivityRow]
  @financial_summary: Accounting::PropertySummaryQuery::SummaryResult
  @security_deposits_held_cents: Integer
  @active_years: Array[Integer]
  @schedule_e_result: TaxReporting::ScheduleEResult
  @tax_profile: PropertyTaxProfile?
  @form_definition: TaxReporting::ScheduleEFormDefinition
  @rents_received: BigDecimal
  @utility_reimbursements: BigDecimal
  @total_income: BigDecimal
  @expenses_by_category: Hash[String, BigDecimal]
  @total_expenses: BigDecimal
  @net_income: BigDecimal

  def index: () -> void
  def show: () -> void
  def schedule_e: () -> void
  def schedule_e_pdf: () -> void
  def new: () -> void
  def edit: () -> void
  def create: () -> void
  def update: () -> void
  def destroy: () -> void

  private

  def set_property: () -> Property
  def property_params: () -> ActionController::Parameters
  def unit_params: () -> ActionController::Parameters?
end
