class ReceiptsController < ApplicationController
  include IndexFilters
  @receipts: ActiveRecord::Relation
  @receipt: Receipt
  @replacement_receipt: Receipt
  @tenancy: Tenancy?
  @tenancies: ActiveRecord::Relation
  @parties: ActiveRecord::Relation
  @properties: Property::ActiveRecord_Relation
  @active_years: Array[Integer]
  @filter_range: Accounting::DateRange?
  @filters: Hash[Symbol, untyped]
  @page: Integer
  @per_page: Integer
  @total_count: Integer
  @total_pages: Integer
  @received_total_cents: Integer
  @voided_total_cents: Integer
  @balance_cents: Integer?
  @recent_activity_rows: Array[Accounting::TenantReceivableActivityQuery::StatementRow]

  def index: () -> void
  def show: () -> void
  def new: () -> void
  def create: () -> void
  def correction: () -> void
  def correct: () -> void
  def void: () -> void

  private

  def filtered_receipts: () -> untyped
  def set_tenancy: () -> void
  def set_receipt: () -> void
  def receipt_params: () -> ActionController::Parameters
  def load_form_collections: () -> void
  def render_receipt_failure: () -> void
end
