class ScheduledRentsController < ApplicationController
  @scheduled_rents: ScheduledRent::ActiveRecord_Relation
  @scheduled_rent: ScheduledRent

  def index: () -> untyped

  def show: () -> untyped

  private

  def set_scheduled_rent: () -> untyped
end
