class TenanciesController < ApplicationController
  @tenancies: Tenancy::ActiveRecord_Relation
  @balances: Hash[Integer, Integer]
  @tenancy: Tenancy
  @properties: Property::ActiveRecord_Relation
  @parties: Party::ActiveRecord_Relation
  @recent_statement: Accounting::TenantReceivableActivityQuery::StatementResult
  @recent_activity_rows: Array[Accounting::TenantReceivableActivityQuery::StatementRow]
  @current_rent_term: RentTerm?
  @balance_cents: Integer
  @security_deposit_held_cents: Integer
  @date_range: Accounting::DateRange
  @statement: Accounting::TenantReceivableActivityQuery::StatementResult
  @financial_activity: Accounting::TenancyActivityQuery::ActivityResult
  @view_mode: String

  def index: () -> void
  def show: () -> void
  def statement: () -> void
  def new: () -> void
  def edit: () -> void
  def create: () -> void
  def update: () -> void
  def destroy: () -> void

  private

  def set_tenancy: () -> Tenancy
  def set_form_data: () -> void
  def tenancy_create_params: () -> ActionController::Parameters
  def tenancy_update_params: () -> ActionController::Parameters
  def participants_params: () -> Array[ActionController::Parameters | Hash[Symbol, untyped]]
  def initial_rent_params: () -> (ActionController::Parameters | Hash[Symbol, untyped])
end
