module PaymentIngestions
  class FormDataQuery
    class Result
      def parties: () -> (Party::ActiveRecord_Relation | Party::ActiveRecord_Associations_CollectionProxy)
      def tenancies: () -> Tenancy::ActiveRecord_Relation
      def party_tenancies_map: () -> Hash[Integer, Array[Integer]]
      def tenancy_parties_map: () -> Hash[Integer, Array[Integer]]
      def self.new: (
        parties: Party::ActiveRecord_Relation | Party::ActiveRecord_Associations_CollectionProxy,
        tenancies: Tenancy::ActiveRecord_Relation,
        party_tenancies_map: Hash[Integer, Array[Integer]],
        tenancy_parties_map: Hash[Integer, Array[Integer]]
      ) -> Result
    end

    def initialize: (user: User) -> void

    def call: () -> Result

    private

    attr_reader user: User

    def party_tenancies_map: () -> Hash[Integer, Array[Integer]]

    def tenancy_parties_map: () -> Hash[Integer, Array[Integer]]
  end
end
