module ImportedTransactions
  class ConfirmService
    @user: User
    @transaction: ImportedTransaction
    @params: Hash[Symbol, untyped]
    @create_aliases: bool
    @requested_alias: String?

    def self.call: (user: User, transaction: ImportedTransaction, ?params: Hash[Symbol, untyped], ?create_alias: bool, ?requested_alias: String?) -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)
    def initialize: (user: User, transaction: ImportedTransaction, ?params: Hash[Symbol, untyped], ?create_alias: bool, ?requested_alias: String?) -> void
    def call: () -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)

    private
    attr_reader user: User
    attr_reader transaction: ImportedTransaction
    attr_reader params: Hash[Symbol, untyped]
    attr_reader requested_alias: String?

    def confirm_receipt: () -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)
    def confirm_security_deposit: () -> (Dry::Monads::Result::Success | Dry::Monads::Result::Failure)
    def create_party_aliases: () -> void
    def create_aliases?: () -> bool
    def create_party_alias: (String? alias_name) -> void
    def success: (untyped data) -> Dry::Monads::Result::Success
    def failure: (String error, Symbol code) -> Dry::Monads::Result::Failure
  end
end
