module PaymentIngestions
  class ConfirmService
    def self.call: (user: User, ingestion: PaymentIngestion, ?create_alias: bool) -> Dry::Monads::Result

    def initialize: (user: User, ingestion: PaymentIngestion, ?create_alias: bool) -> void

    def call: () -> Dry::Monads::Result

    private

    attr_reader user: User
    attr_reader ingestion: PaymentIngestion

    def create_payment: () -> TenantPayment

    def create_aliases: () -> void

    def create_aliases?: () -> bool

    def create_alias: (String? alias_name) -> void

    def success: (untyped data) -> Dry::Monads::Result::Success

    def failure: (untyped error, Symbol code) -> Dry::Monads::Result::Failure
  end
end
