module Leases
  class ScheduledRentSyncService
    def self.call: (Lease lease, ?previously_new_record: bool) -> untyped

    def initialize: (Lease lease, ?previously_new_record: bool) -> void

    def call: () -> untyped

    private

    def first_due_date: () -> Date

    def end_date: () -> Date?
  end
end
