require "rails_helper"

RSpec.describe "Security Deposit Double-Entry Posting Invariants" do
  let(:user) { create(:user) }
  let(:property) { create(:property, user: user) }
  let(:unit) { create(:rentable_unit, property: property) }
  let(:tenancy) { create(:tenancy, rentable_unit: unit) }
  let(:party) { create(:party, user: user) }
  let(:security_deposit) { create(:security_deposit, tenancy: tenancy, required_amount_cents: 200_000) }

  before do
    Accounting::ChartOfAccounts.ensure_for(user)
  end

  describe "double-entry postings generated by orchestrators" do
    it "posts balanced Dr Cash (+), Cr Security Deposits Held (-) on ReceiveService" do
      result = SecurityDepositTransactions::ReceiveService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 100_000,
        occurred_on: Date.new(2026, 1, 1),
        memo: "Custom received memo"
      )

      expect(result).to be_success
      entry = result.value!.data[:journal_entry]
      expect(entry.event_type).to eq("deposit_received")
      expect(entry.occurred_on).to eq(Date.new(2026, 1, 1))
      expect(entry.description).to eq("Custom received memo")

      postings = entry.postings.includes(:account)
      cash_posting = postings.find { |p| p.account.key == "cash" }
      liability_posting = postings.find { |p| p.account.key == "security_deposits_held" }

      expect(cash_posting.amount_cents).to eq(100_000)
      expect(liability_posting.amount_cents).to eq(-100_000)
      expect(cash_posting.party).to eq(party)
      expect(liability_posting.party).to eq(party)
      expect(liability_posting.property_id).to eq(property.id)
    end

    it "posts balanced Dr Security Deposits Held (+), Cr Cash (-) on RefundService" do
      SecurityDepositTransactions::ReceiveService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 100_000,
        occurred_on: Date.new(2026, 1, 1)
      )

      result = SecurityDepositTransactions::RefundService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 40_000,
        occurred_on: Date.new(2026, 1, 5),
        memo: "Custom refund memo"
      )

      expect(result).to be_success
      entry = result.value!.data[:journal_entry]
      expect(entry.event_type).to eq("deposit_refunded")
      expect(entry.description).to eq("Custom refund memo")

      postings = entry.postings.includes(:account)
      cash_posting = postings.find { |p| p.account.key == "cash" }
      liability_posting = postings.find { |p| p.account.key == "security_deposits_held" }

      expect(liability_posting.amount_cents).to eq(40_000)
      expect(cash_posting.amount_cents).to eq(-40_000)
      expect(cash_posting.party).to eq(party)
      expect(liability_posting.party).to eq(party)
      expect(liability_posting.property_id).to eq(property.id)
    end

    it "posts balanced Dr Security Deposits Held (+), Cr Tenant Receivable (-) on ApplyService" do
      SecurityDepositTransactions::ReceiveService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 100_000,
        occurred_on: Date.new(2026, 1, 1)
      )

      charge = Charges::CreateService.call(
        tenancy: tenancy,
        charge_kind: "other",
        amount_cents: 50_000,
        charge_date: Date.new(2026, 1, 2),
        due_on: Date.new(2026, 1, 2),
        description: "Door repair"
      ).value!.data[:charge]

      result = SecurityDepositTransactions::ApplyService.call(
        security_deposit: security_deposit,
        charge: charge,
        amount_cents: 50_000,
        occurred_on: Date.new(2026, 1, 5),
        memo: "Custom apply memo"
      )

      expect(result).to be_success
      entry = result.value!.data[:journal_entry]
      expect(entry.event_type).to eq("deposit_applied")
      expect(entry.description).to eq("Custom apply memo")

      postings = entry.postings.includes(:account)
      ar_posting = postings.find { |p| p.account.key == "tenant_receivable" }
      liability_posting = postings.find { |p| p.account.key == "security_deposits_held" }

      expect(liability_posting.amount_cents).to eq(50_000)
      expect(ar_posting.amount_cents).to eq(-50_000)
      expect(ar_posting.party).to be_nil
      expect(liability_posting.property_id).to eq(property.id)
    end

    it "reverses and replaces balanced entries on CorrectService" do
      rec_res = SecurityDepositTransactions::ReceiveService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 100_000,
        occurred_on: Date.new(2026, 1, 1)
      )
      orig_txn = rec_res.value!.data[:transaction]

      correct_res = SecurityDepositTransactions::CorrectService.call(
        transaction: orig_txn,
        amount_cents: 120_000,
        occurred_on: Date.new(2026, 1, 1)
      )

      expect(correct_res).to be_success
      replacement = correct_res.value!.data[:replacement]
      reversal_entry = correct_res.value!.data[:reversal]

      expect(reversal_entry.postings.sum(:amount_cents)).to eq(0)
      expect(replacement.journal_entries.first.postings.sum(:amount_cents)).to eq(0)
      expect(Accounting::SecurityDepositBalanceQuery.call(tenancy: tenancy)).to eq(120_000)
    end
  end

  describe "invariants preventing invalid postings" do
    it "rejects refund against zero held liability" do
      result = SecurityDepositTransactions::RefundService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 50_000,
        occurred_on: Date.current
      )

      expect(result).to be_failure
      expect(result.failure.code).to eq(:negative_deposit_liability)
      expect(Accounting::SecurityDepositBalanceQuery.call(tenancy: tenancy)).to eq(0)
      expect(JournalEntry.where(source_type: "SecurityDepositTransaction").count).to eq(0)
    end

    it "rejects application against zero held liability" do
      charge = Charges::CreateService.call(
        tenancy: tenancy,
        charge_kind: "other",
        amount_cents: 50_000,
        charge_date: Date.current,
        due_on: Date.current
      ).value!.data[:charge]

      result = SecurityDepositTransactions::ApplyService.call(
        security_deposit: security_deposit,
        charge: charge,
        amount_cents: 50_000,
        occurred_on: Date.current
      )

      expect(result).to be_failure
      expect(result.failure.code).to eq(:negative_deposit_liability)
      expect(JournalEntry.where(source_type: "SecurityDepositTransaction").count).to eq(0)
    end

    it "rejects application exceeding tenancy A/R" do
      SecurityDepositTransactions::ReceiveService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 100_000,
        occurred_on: Date.new(2026, 1, 1)
      )

      charge = Charges::CreateService.call(
        tenancy: tenancy,
        charge_kind: "other",
        amount_cents: 50_000,
        charge_date: Date.new(2026, 1, 2),
        due_on: Date.new(2026, 1, 2)
      ).value!.data[:charge]

      # Pay $300 towards the $500 charge so remaining A/R is only $200
      Receipts::CreateService.call(
        tenancy: tenancy,
        payer_party: party,
        amount_cents: 30_000,
        received_on: Date.new(2026, 1, 3),
        payment_method: "check"
      )

      result = SecurityDepositTransactions::ApplyService.call(
        security_deposit: security_deposit,
        charge: charge,
        amount_cents: 30_000,
        occurred_on: Date.new(2026, 1, 5)
      )

      expect(result).to be_failure
      expect(result.failure.code).to eq(:exceeds_tenancy_balance)
      expect(charge.security_deposit_applications.count).to eq(0)
    end

    it "rejects application against inactive or unposted charge" do
      SecurityDepositTransactions::ReceiveService.call(
        security_deposit: security_deposit,
        party: party,
        amount_cents: 100_000,
        occurred_on: Date.new(2026, 1, 1)
      )

      charge = Charges::CreateService.call(
        tenancy: tenancy,
        charge_kind: "other",
        amount_cents: 50_000,
        charge_date: Date.new(2026, 1, 2),
        due_on: Date.new(2026, 1, 2)
      ).value!.data[:charge]

      Charges::VoidService.call(charge: charge, reason: "Mistake")

      result = SecurityDepositTransactions::ApplyService.call(
        security_deposit: security_deposit,
        charge: charge.reload,
        amount_cents: 50_000,
        occurred_on: Date.new(2026, 1, 5)
      )

      expect(result).to be_failure
      expect(result.failure.code).to eq(:invalid_charge_state)
    end
  end
end
