module Expenses
  class SaveService
    def self.call: (expense: Expense) -> Dry::Monads::Result

    def initialize: (expense: Expense) -> void

    def call: () -> Dry::Monads::Result

    private

    attr_reader expense: Expense
  end
end
