module ActiveRecord
  class Base
    def accounting_user: () -> User?
    def user: () -> User?
    def user_id: () -> Integer?
  end

  class Relation
    module Methods[Model, PrimaryKey]
      def each: () { (Model) -> void } -> void
    end
  end

  module Associations
    class Preloader
      def initialize: (?records: untyped, ?associations: untyped) -> void
      def call: () -> untyped
    end
  end
end
