module Properties
  class TaxesController < ApplicationController
    @property: Property
    @year: Integer
    @tax_profile: PropertyTaxProfile?
    @status: Reports::ScheduleEStatusesQuery::ScheduleEStatus
    @active_years: Array[Integer]
    @pdf_available: bool

    def show: () -> void

    private

    def set_property: () -> void
  end
end
