module PaymentIngestions
  module Parsers
    class ChaseStatement < Base
      def parse: (String pdf_text) -> Array[untyped]

      private

      def resolve_date: (String date_str, Date start_date, Date end_date) -> Date
    end
  end
end
